### ISSUE TITLE
is the anonymous function inside find-href necessary ?

### ISSUE THREAD

**Issue by geraldodev** [venantius/accountant#11]
Hi,

Given find-href
```
(defn- find-href
  "Given a DOM element that may or may not be a link, traverse up the DOM tree
  to see if any of its parents are links. If so, return the href content."
  [e]
  ((fn [e]
     (if-let [href (.-href e)]
        href
        (when-let [parent (.-parentNode e)]
           (recur parent)))) (.-target e)))
```
Is the fn [e] function inside the body necessary ?
I'm asking because, you don't return it, calling it immediately and it has the same signature of the find-href, even the variable name is the same.

A recur to find-href wouldn't suffice ?

Kind regards,

Geraldo

**Comment by venantius** [comment]
That is an excellent observation! I'll take a look at this over the weekend.

**Comment by venantius** [comment]
Resolved https://github.com/venantius/accountant/commit/9b4b68da7cca30926fcace113959a53c625f1de3
