### ISSUE TITLE
accountant/navigate! reuses existing query params, instead of resetting it

### ISSUE THREAD

**Issue by tolgap** [venantius/accountant#19]
Here's a small scenario:

I have a search input. The input changes the URL in its `on-change` attribute. The URL is changed from:

`localhost:3449/` to `localhost:3449/?q=t`

But when I keep tying the word `test` into the search input, the URL changes to:

`localhost:3449/?q=t?q=te?q=tes?q=test`.

I have managed to track the issue down to this line in `core.cljs` line `108`:

```
(let [token (.getToken history)])
```

It seems the `Html5History` API from the Google Closure Library does not keep track/return the query string when calling `getToken` on it, because it always returns `"/"`, instead of `"/?q=t"` etc.

Is there any way I can work around this for now? I don't know if the issue is in the GCL `Html5History` API, or Accountant, or that I'm doing something wrong.

**Comment by venantius** [comment]
Huh. That is pretty weird. I'm not totally sure where the bug here is either - could also be in Secretary. Will have to do some debugging.

**Comment by logaan** [comment]
I'm hitting this bug as well.

**Comment by bago2k4** [comment]
I use a custom transformer for the Html5History object:
https://github.com/open-company/open-company-web/blob/mainline/src/open_company_web/router.cljs
inspired by this:
https://github.com/Sparrho/supper-demo/blob/master/src-cljs/supper/history.cljs

**Comment by philjackson** [comment]
Wondering if anyone figured this out?

**Comment by venantius** [comment]
I'd welcome a PR to fix this.

**Comment by pharcosyle** [comment]
I solved this problem adding the following code above by accountant/configure-navigation! call:

`(set! accountant/history.transformer_
      (let [transformer (goog.history.Html5History.TokenTransformer.)]
        (set! (.. transformer -retrieveToken)
              (fn [path-prefix location]
                (str (.-pathname location) (.-search location))))
        (set! (.. transformer -createUrl)
              (fn [token path-prefix location]
                (str path-prefix token)))
        transformer))`

bago2k4's links were very helpful.

**Comment by acron0** [comment]
@pharcosyle 's code fixes it. Thank you!

**Comment by venantius** [comment]
I believe this has been resolved by #48.
