### ISSUE TITLE
Secretary 2

### ISSUE THREAD

**Issue by bago2k4** [venantius/accountant#2]
Hi,
did you try to migrate this to secretary 2? I did some work on this [here](https://github.com/bago2k4/accountant/tree/secretary-2) but i'm stuck with this [issue](https://github.com/gf3/secretary/issues/77): i need to know what is the best replacement for the `locate-route` function in secretary 2.
Is it ok with you if i open a PR when i'm done or you want to keep this only for secretary 1?
Great jar, thanks!

**Comment by venantius** [comment]
I'd love to support Secretary 2. I don't know what the replacement is for `locate-route` in Secretary 2. If it turns out they don't support it we could always bring the logic for that into Accountant and go from there, assuming it's still functional. Does that sound reasonable?

**Comment by bago2k4** [comment]
Yeah, or i can open a PR with Secretary too to add the function. I don't know how long that could take though, let's see if they reply to my issue.
I'll let you know when i decide how to proceed.
Thanks for now

**Comment by venantius** [comment]
Sounds good, keep me posted.

**Comment by venantius** [comment]
This issue was addressed by https://github.com/venantius/accountant/commit/8705431db7122e195fc90d5a25d27a1f1226b81a
