### ISSUE TITLE
Browser doesn't scroll to anchors on the page

### ISSUE THREAD

**Issue by PEZ** [venantius/accountant#25]
I have an issue that I don't know if it is due to accountant or something else in my setup. When clicking links leading to anchors on the page, the browser doesn’t scroll. If the anchor is on the same page, it’s like clicking a dead link. If the anchor is on another page on the site/app then the new page is rendered, but scrolled to wherever the previous page were scrolled. Something like so:
#### Fixture:
- A long/tall page `/A` containg:
  - a link `/A#a` (high up on the page)
  - an anchor `a` (farther down the page).
  - a link `/B#b` (far down on the page)
- Page `/B` containing:
  - an anchor `b` (high up on the page)
#### Tests:
1. On page `/A`, click the link `/A#a`
   1. **Expected**: Page `/A` scrolls down to anchor `a`
   2. **Result**: Nothing happens.
2. On page `/A`, click the link `/B#b`
   1. **Expected**: Page `/B` opens, scrolled up to anchor `b`
   2. **Result**: Page `/B` opens, scroll doesn't change (so showing content somehwere far down on the page). 
#### Notes

It isn't necessarily about clicking. It behaves the same if I type the url:s in the browser's location bar, or if I enter something like `accountant.core.history.setToken("/A#a")` from the dev console.

_**However**, if I enter `window.location = "/A#a"` in the dev console it does scroll to the anchor._

**Comment by venantius** [comment]
It not being about clicking isn't surprising - although it seems like Accountant only overrides clicking behavior, it actually overrides basically all user-level navigation transitions. You can bypass these, as you noted, by directly interacting with the underlying system and explicitly setting `window.location`.

My suspicion is that this is somehow Accountant related, but I couldn't tell how you to fix it off the top of my head. Investigation and PRs welcome :)

**Comment by RyanBertrand** [comment]
I also ran into this issue.  Setting window.location on-click instead of using the href with the anchor works.  Thanks @PEZ

**Comment by venantius** [comment]
Any guidance on whether this was resolved by #48?

**Comment by luciodale** [comment]
My guess is that it hasn't been fixed yet, as I am experiencing the same bug. A workaround is to have an `on-click` function that does the following: `(js/window.location.assign "#id"))`
