### ISSUE TITLE
prevent default?

### ISSUE THREAD

**Issue by jdkealy** [venantius/accountant#27]
Hi, 

I'd like to add a click handler that prevents navigation when -- for example -- the user is not signed in. It seems that the on-click gets fired after the navigation occurs, so I'm wondering if there's any way to do this. Many thanks.

**Comment by venantius** [comment]
My naive response would be that you should just make the thing the user is clicking a button, not a link, and have your on-click handler for the button trigger Accountant's `navigate!` function if the user is logged in.
