### ISSUE TITLE
window.location.port and goog.uri.getPort defaults are not equivalent.

### ISSUE THREAD

**Issue by minikomi** [venantius/accountant#36]
In google chrome at least, when no port is specified on a link:

* `window.location.port` defaults to `""` [ref](https://html.spec.whatwg.org/multipage/browsers.html#dom-location-port)
* `uri.getPort` defaults to null [ref](https://google.github.io/closure-library/api/goog.Uri.html#getPort)

The [test for port equality](https://github.com/venantius/accountant/blob/master/src/accountant/core.cljs#L95) fails when no port is specified for the link, preventing accountant from stepping in.

**Comment by venantius** [comment]
Open to a PR :D?

**Comment by minikomi** [comment]
Sure, I can do that, but I'd like to get @nicorikken in too -- I can't get 1.8.0 to work with or without port in any browser since `window.location.port` is always a string and `goog.Uri.getPort` is always a number.

**Comment by venantius** [comment]
Resolved by #38. Will release this evening. If I forget feel free to remind me.
