### ISSUE TITLE
nav-handler doesn't receive manually changed hash fragment

### ISSUE THREAD

**Issue by meeseekz** [venantius/accountant#44]
For example when the URL is `/abc` and I change it in the browser to `/abc#123` the nav-handler only receives `"/abc"`. When clicking on a link with href `/abc#123` OTOH the nav-handler gets the full URL.

**Comment by venantius** [comment]
I think this is related to #19, which was resolved by #48. There's a new release out now that should address this; please let me know if that turns out not to be the case.
