### ISSUE TITLE
Navigating back in history looses the query-params in :nav-handler

### ISSUE THREAD

**Issue by DrTom** [venantius/accountant#47]
Steps to reproduce the problem:

1. open `/a?x=1` for example, this will call the specified nav-handler as expected with the path `/a?x=1` 
2. follow some link, say `/b?y=1`; this will call the specified nav-handler as expected with the path `/b?y=1` 
3. now hit the back button: the browser will show the path `/a?x=1`, but the nav-handler will be called with the path `/a`; note the missing query parameters

Environment: tested under Mac OS with both Chrome 60 and Firefox 56 (developer edition); clojurescript "1.9.854"; 

Seems to be similar to https://github.com/venantius/accountant/issues/23

**Comment by venantius** [comment]
@DrTom PEZ was working on a PR for this but then stopped cleaning it up - if you wanted to "rescue" it https://github.com/venantius/accountant/pull/24 -- either in its current form or by taking a fresh stab at it, I'd accept it.

**Comment by DrTom** [comment]
I ressurected much of PEZ coded and added a fix for the query-parameters too in https://github.com/venantius/accountant/pull/48.

**Comment by venantius** [comment]
#48 has now been merged and this is resolved.
