### ISSUE TITLE
Manually changing url.

### ISSUE THREAD

**Issue by Chyzwar** [venantius/accountant#5]
Hi

It should be possible to use secretary and accountant for routing when user type url manually?

**Comment by venantius** [comment]
I don't understand what you're asking. Could you clarify?

**Comment by Chyzwar** [comment]
When user type in url in browser address bar like: /login
then accountant should try to match this to existing routes.

**Comment by venantius** [comment]
It does, if you have your secretary routes defined. That's like half the point of the library :stuck_out_tongue: 

If you're not seeing that behavior, show me what you're doing with secretary and accountant, because it's probably configured wrong.

**Comment by Chyzwar** [comment]
```cljs
(ns ^:figwheel-always whisper.routes
  (:require [om.core :as om :include-macros true]
            [om.dom :as dom :include-macros true]
            [secretary.core :as sec :refer-macros [defroute]]
            [accountant.core :as accountant]))

(accountant/configure-navigation!)

(defn widget [data owner]
  (reify
    om/IRender
    (render [this]
            (dom/h1 nil (:text data)))))

(defroute main-page "/" []
  (om/root widget {:text "Main Page"}
           {:target (. js/document (getElementById "app"))})
  
  (js/console.log (str "Main Page")))


(defroute login-page "/login" []
  (om/root widget {:text "Login Page"}
           {:target (. js/document (getElementById "app"))})
  (js/console.log (str "Login Page")))


(defroute wildcard "*" []
  (accountant/navigate! "/"))

(accountant/navigate! "/login")
```

**Comment by venantius** [comment]
I do think having the `navigate!` call there at the end is probably sub-optimal. What I have on load time is `(secretary/dispatch! (.-pathname (.-location js/window)))` but that's your call. 

The only other thing I can think is that your wildcard route is firing somehow. What actually happens when you try to load `/login`? Does anything show up in the console?

**Comment by Chyzwar** [comment]
When I start figwhell, page is loaded to /login route. But whenever I click on page area I get the error in screenshot. Strngly error is only happen when I click on page. 

![error](https://cloud.githubusercontent.com/assets/5990767/10653689/dae603dc-7859-11e5-80ce-fcb1bf68fe14.png)


When I remove /login from url leaving only http://localhost:3449 page is loaded but no root or wildcard route is do not trigger. 
To see console.logs you need to add: (enable-console-print!)

**Comment by venantius** [comment]
I now understand your issue. (accountant/navigate!) is intended for use as a reactor; it's not intended to be used in the initial page load. A better example of its use can be found here:

```clojure
(defn go-to-repo-dashboard!
  [username repo]
  (accountant/navigate!
   (string/format "/gh/%s/%s" username repo)))
```

Instead, you should use the initial dispatch! call that I pasted above for your initial page load:

```clojure
(accountant/configure-navigation!)

(defn widget [data owner]
  (reify
    om/IRender
    (render [this]
            (dom/h1 nil (:text data)))))

(defroute main-page "/" []
  (om/root widget {:text "Main Page"}
           {:target (. js/document (getElementById "app"))})

  (js/console.log (str "Main Page")))


(defroute login-page "/login" []
  (om/root widget {:text "Login Page"}
           {:target (. js/document (getElementById "app"))})
  (js/console.log (str "Login Page")))


(defroute wildcard "*" []
  (accountant/navigate! "/"))

(secretary/dispatch! (.-pathname (.-location js/window)))
```

I've tested this and it works great once you change it. 

There's a good question here about whether `accountant/navigate!` *should* do the thing you expect it to here, and to be totally honest I don't understand why it doesn't. I'll have to look into it further.

**Comment by venantius** [comment]
Actually, I take that back. `accountant/navigate!` does work fine for me as well.

**Comment by venantius** [comment]
Okay, yeah, sorry, I'm completely unable to reproduce your issue. The code you've provided works fine on my machine.

**Comment by Chyzwar** [comment]
thanks, for your time. This is probably related to figwheel ,like it loose
state of history of something like that.

> On Oct 22 2015, at 1:34 am, Ursa americanus kermodei
&lt;notifications@github.com&gt; wrote:  

>

> Okay, yeah, sorry, I'm completely unable to reproduce your issue. The code
you've provided works fine on my machine.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/venanti
us/accountant/issues/5#issuecomment-150063393).![](https://github.com/notifica
tions/beacon/AFtpbzq6z0QceG6TKyw_jogwQizknfwUks5o-CaWgaJpZM4GTWCZ.gif)
