### ISSUE TITLE
Bad url comparison in `prevent-reload-on-known-path`.

### ISSUE THREAD

**Issue by frankitox** [venantius/accountant#62]
Hi! It seems that there's a typo in `prevent-reload-on-known-path`. When comparing the current URL and the one the user clicked if they are different, it calls `.setToken` in the history. To build the current URL you use `(str (.-pathname loc) (.-query loc) (.-hash loc))`, where `loc` is `js/window.location`. It should be `.-search` instead of `.-query`.

https://github.com/venantius/accountant/blob/d62f5a9d4c8503ae1f243c39cb8b315ea2ead967/src/accountant/core.cljs#L90-L103

To reproduce the issue you can try going from a URL such as `https://example.com?hey`  to `https://example.com`. Then, the `path-exists?` fn gets executed, but not the `nav-handler`.

For now I'll opt on calling `(set! navigate-listener-key my-own-prevent-fn)` after my call to `configure-navigation!`.

**Comment by iku000888** [comment]
Taking a look at this to understand the problem...

**Comment by frankitox** [comment]
Hi! You're a maintainer of the library? Tell me if my explanation isn't enough. I need a confirmation that this is a bug. The PR should be straightforward, is just changing `.-search` for `.-query`.

**Comment by iku000888** [comment]
@frankitox 

Yes I do help with some maintenance and can merge PRs.

Back to this problem, I agree with you that it is a bug as there is no such .-query property on location.href and should be .-search.

https://developer.mozilla.org/en-US/docs/Web/API/Location

I would be happy to test out and merge the change if you could send a PR!

**Comment by iku000888** [comment]
Closable once we cut a release.

**Comment by venantius** [comment]
@frankitox sorry for the delay, I've just cut a new release. 0.2.5 is now up on Clojars.
